### ISSUE TITLE
Cannot Start The Application

### ISSUE THREAD

**Issue by Tanmayb05** [LarsRosenkilde/Python-Apps#1]
I downloaded ffmpeg and PyQt5 adnd youtube-dl as well. When i start main.py, cmd opens and closes immediately, no window opens.

**Comment by bytesenseidk** [comment]
> I downloaded ffmpeg and PyQt5 adnd youtube-dl as well. When i start main.py, cmd opens and closes immediately, no window opens.

Did you install from the requirements.txt file?

**Comment by bytesenseidk** [comment]
> I downloaded ffmpeg and PyQt5 adnd youtube-dl as well. When i start main.py, cmd opens and closes immediately, no window opens.

I have an idea you just open the script directly, am i right? You need to execute the script from a terminal, like: python YoutubeDownloader.py 
If you read the README, i've written a full guide on how you can compile it to an exe file 👍
